#!/usr/bin/env bash
# Builds the sidecar launcher binary for the current host triple (and
# any requested cross-compile triples) and drops it under
# `apps/desktop/src-tauri/binaries/clio-agent-<triple>{.exe}` so that
# Tauri's externalBin bundling can pick it up.
#
# Usage:
#   ./fetch-sidecar.sh              # host triple only
#   ./fetch-sidecar.sh --all        # host + all release triples
#   ./fetch-sidecar.sh <triple>...  # specific triples
#
# Triple <-> GOOS/GOARCH map:
#   x86_64-pc-windows-msvc   -> windows/amd64
#   aarch64-pc-windows-msvc  -> windows/arm64
#   aarch64-apple-darwin     -> darwin/arm64
#   x86_64-apple-darwin      -> darwin/amd64
#   x86_64-unknown-linux-gnu -> linux/amd64
#   aarch64-unknown-linux-gnu -> linux/arm64
#
# Also probes the host for an actual `clio-agent-gact` binary and
# writes `apps/desktop/src-tauri/sidecar.lock` with the resolved path
# (or the install-from-develop instruction when absent).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/sidecar-launcher"
OUT="$ROOT/src-tauri/binaries"
LOCK="$ROOT/src-tauri/sidecar.lock"

mkdir -p "$OUT"

### Supported target triples ###
# macOS runners ship bash 3.2 which doesn't support associative arrays,
# so the triple → (GOOS, GOARCH, ext) table is a plain case statement.
ALL_TRIPLES="x86_64-pc-windows-msvc aarch64-pc-windows-msvc aarch64-apple-darwin x86_64-apple-darwin x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu"

triple_to_spec() {
  case "$1" in
    x86_64-pc-windows-msvc)     echo "windows amd64 .exe" ;;
    aarch64-pc-windows-msvc)    echo "windows arm64 .exe" ;;
    aarch64-apple-darwin)       echo "darwin  arm64 " ;;
    x86_64-apple-darwin)        echo "darwin  amd64 " ;;
    x86_64-unknown-linux-gnu)   echo "linux   amd64 " ;;
    aarch64-unknown-linux-gnu)  echo "linux   arm64 " ;;
    *) echo "" ;;
  esac
}

host_triple() {
  case "$(uname -s)" in
    Linux)   echo "x86_64-unknown-linux-gnu" ;;
    Darwin)
      if [ "$(uname -m)" = "arm64" ]; then
        echo "aarch64-apple-darwin"
      else
        echo "x86_64-apple-darwin"
      fi
      ;;
    MINGW*|MSYS*|CYGWIN*) echo "x86_64-pc-windows-msvc" ;;
    *) echo "unknown" ;;
  esac
}

build_one() {
  local triple="$1"
  local spec
  spec="$(triple_to_spec "$triple")"
  if [ -z "$spec" ]; then
    echo "fetch-sidecar: unknown target triple: $triple" >&2
    return 1
  fi
  # `spec` is whitespace-separated: <goos> <goarch> <ext>. Read with
  # default IFS so the trailing empty-string ext works on Linux/macOS.
  local goos goarch ext
  goos=$(echo "$spec" | awk '{print $1}')
  goarch=$(echo "$spec" | awk '{print $2}')
  ext=$(echo "$spec" | awk '{print $3}')
  local out="$OUT/clio-agent-${triple}${ext}"
  echo "[fetch-sidecar] building $triple -> $out (GOOS=$goos GOARCH=$goarch)"
  (
    cd "$SRC"
    GOWORK=off GOOS="$goos" GOARCH="$goarch" CGO_ENABLED=0 \
      go build -trimpath -ldflags='-s -w' -o "$out" .
  )
}

resolve_gact_bin() {
  if [[ -n "${CLIO_AGENT_GACT_BIN:-}" ]] && [[ -x "$CLIO_AGENT_GACT_BIN" ]]; then
    echo "$CLIO_AGENT_GACT_BIN"
    return
  fi
  if command -v clio-agent-gact >/dev/null 2>&1; then
    command -v clio-agent-gact
    return
  fi
  case "$(uname -s)" in
    Linux)
      local p="$HOME/.local/share/clio/clio-agent/.venv/bin/clio-agent-gact"
      [[ -x "$p" ]] && { echo "$p"; return; } ;;
    Darwin)
      local p="$HOME/Library/Application Support/clio/clio-agent/.venv/bin/clio-agent-gact"
      [[ -x "$p" ]] && { echo "$p"; return; } ;;
    MINGW*|MSYS*|CYGWIN*)
      local p="${LOCALAPPDATA:-$HOME/AppData/Local}/clio/clio-agent/.venv/Scripts/clio-agent-gact.exe"
      [[ -f "$p" ]] && { echo "$p"; return; }
      local devp="/d/Libraries/Documents/projects/clio-agent/.venv/Scripts/clio-agent-gact.exe"
      [[ -f "$devp" ]] && { echo "$devp"; return; } ;;
  esac
  echo ""
}

write_lock() {
  local resolved="$1"
  local now
  now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  cat >"$LOCK" <<EOF
# Generated by apps/desktop/scripts/fetch-sidecar.sh — do not hand-edit.
#
# This file pins the sidecar resolution context for reproducibility.
# The launcher binary in apps/desktop/src-tauri/binaries/ executes the
# clio-agent-gact server at runtime; this lockfile records what was
# discoverable on the build host so reviewers can see whether the
# build is bound to a system install or a fresh develop checkout.

generated_at = "$now"
host_triple = "$(host_triple)"
resolved_clio_agent_gact = "$resolved"
contract = "GACT v0.2"
source_branch = "develop"
source_repo = "https://github.com/iowarp/clio-agent"
install_recipe = "CLIO_REF=develop curl -fsSL https://raw.githubusercontent.com/iowarp/clio-agent/main/install/install.sh | bash"
windows_install_recipe = '\$env:CLIO_REF = ''develop''; irm https://raw.githubusercontent.com/iowarp/clio-agent/main/install/install.ps1 | iex'
EOF
}

main() {
  local triples
  if [ $# -eq 0 ]; then
    triples="$(host_triple)"
  elif [ "$1" = "--all" ]; then
    triples="$ALL_TRIPLES"
  else
    triples="$*"
  fi

  for t in $triples; do
    build_one "$t"
  done

  local resolved
  resolved="$(resolve_gact_bin)"
  write_lock "$resolved"

  if [[ -z "$resolved" ]]; then
    echo "[fetch-sidecar] WARNING: clio-agent-gact not resolved on this host." >&2
    echo "[fetch-sidecar] The launcher will resolve at runtime, but install" >&2
    echo "[fetch-sidecar] clio-agent@develop via the upstream installer:" >&2
    echo "[fetch-sidecar]   CLIO_REF=develop bash <(curl -fsSL .../install.sh)" >&2
  else
    echo "[fetch-sidecar] resolved clio-agent-gact: $resolved"
  fi
}

main "$@"
