import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:1440,height:900}, colorScheme:'dark' });
const errs=[]; p.on('pageerror',e=>errs.push(String(e)));
await p.goto('http://127.0.0.1:4191/',{waitUntil:'networkidle'});
await p.getByTestId('connect-url').fill('http://127.0.0.1:17900');
await p.getByTestId('connect-submit').click();
await p.getByRole('navigation',{name:/workspaces/i}).waitFor({timeout:20000});
await p.waitForTimeout(1200);
const h = async () => (await p.locator('.composer__frame').boundingBox())?.height;
await p.locator('textarea').focus();
const before = await h();
await p.keyboard.press('Shift+Tab');
await p.waitForTimeout(400);
const after = await h();
await p.screenshot({path:'screenshots/visual-check/composer-expanded.png', clip:{x:300,y:560,width:1140,height:340}});
await p.keyboard.press('Shift+Tab');
await p.waitForTimeout(400);
const back = await h();
console.log('frame height collapsed / expanded / collapsed:', Math.round(before), Math.round(after), Math.round(back));
console.log('composer still bottom-anchored while expanded:', await p.evaluate(() => {
  const c = document.querySelector('.composer')?.getBoundingClientRect();
  return c ? Math.round(900 - c.bottom) <= 2 : null;
}));
console.log('console errors:', errs.length, errs.slice(0,2));
await b.close();
