import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:1440,height:900}, colorScheme:'dark' });
const errs=[]; p.on('pageerror',e=>errs.push(String(e)));
await p.goto('http://127.0.0.1:4191/',{waitUntil:'networkidle'});
await p.getByTestId('connect-url').fill('http://127.0.0.1:17900');
await p.getByTestId('connect-submit').click();
await p.getByRole('navigation',{name:/workspaces/i}).waitFor({timeout:20000});
await p.waitForTimeout(1500);
console.log('footer:', (await p.getByTestId('rail-connections').textContent())?.trim());
await p.getByTestId('rail-connections').click();
await p.waitForTimeout(600);
const items = await p.getByRole('menuitem').allTextContents();
console.log('swap menu items:', JSON.stringify(items));
await p.screenshot({path:'screenshots/visual-check/connection-swap.png', clip:{x:0,y:700,width:520,height:200}});
console.log('console errors:', errs.length, errs.slice(0,2));
await b.close();
