"""Static manifest for the visual-loop acceptance corpus."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from visual_corpus_artifacts import looks_like_visual_artifact


@dataclass(frozen=True)
class CorpusGroup:
    name: str
    description: str
    required: tuple[str, ...]


STRICT_LIVE_REPORTS: tuple[str, ...] = (
    "visual_loop/screenshots/live_observability_clio_semantic_live_events.strict.report.md",
)


def manifest_artifacts() -> tuple[str, ...]:
    artifacts: set[str] = set()
    for group in CORPUS_GROUPS:
        artifacts.update(group.required)
    artifacts.update(STRICT_LIVE_REPORTS)
    return tuple(sorted(artifact for artifact in artifacts if looks_like_visual_artifact(artifact)))


def existing_visual_artifacts(root: Path) -> tuple[str, ...]:
    artifacts: set[str] = set()
    for rel_dir in ("visual_loop/tapes", "visual_loop/screenshots"):
        base = root / rel_dir
        if not base.exists():
            continue
        for path in base.iterdir():
            if not path.is_file():
                continue
            rel = path.relative_to(root).as_posix()
            if looks_like_visual_artifact(rel):
                artifacts.add(rel)
    return tuple(sorted(artifacts))


CORPUS_GROUPS: tuple[CorpusGroup, ...] = (
    CorpusGroup(
        name="conversation_tools",
        description="long transcript scrolling, tool summaries, and detail expansion",
        required=(
            "visual_loop/tapes/semantic_long_transcript_scroll.tape",
            "visual_loop/screenshots/semantic_long_transcript_bottom.png",
            "visual_loop/screenshots/semantic_long_transcript_scrolled_up.png",
            "visual_loop/screenshots/semantic_long_transcript_after_pagedown.png",
            "visual_loop/screenshots/semantic_long_transcript_after_g.png",
            "visual_loop/tapes/semantic_live_events.tape",
            "visual_loop/screenshots/semantic_live_events_thinking.png",
            "visual_loop/screenshots/semantic_live_events_tool_started.png",
            "visual_loop/screenshots/semantic_live_events_tool_result.png",
            "visual_loop/screenshots/semantic_live_events_final.png",
            "visual_loop/tapes/clio_semantic_live_events.tape",
            "visual_loop/screenshots/clio_semantic_live_events_running.png",
            "visual_loop/screenshots/clio_semantic_live_events_final.png",
            "visual_loop/tapes/semantic_detail_copy.tape",
            "visual_loop/screenshots/semantic_detail_copy.png",
            "visual_loop/tapes/semantic_conversation_block_copy.tape",
            "visual_loop/screenshots/semantic_conversation_block_copy.png",
            "visual_loop/tapes/semantic_conversation_footer_actions.tape",
            "visual_loop/screenshots/semantic_conversation_footer_actions.png",
            "visual_loop/tapes/semantic_mcp_reconnect.tape",
            "visual_loop/screenshots/semantic_mcp_reconnect_detail.png",
            "visual_loop/screenshots/semantic_mcp_reconnect_done.png",
            "visual_loop/tapes/semantic_session_summary.tape",
            "visual_loop/screenshots/semantic_session_summary.png",
            "visual_loop/tapes/semantic_event_detail.tape",
            "visual_loop/screenshots/semantic_event_detail.png",
            "visual_loop/screenshots/semantic_event_detail_evidence.png",
            "visual_loop/tapes/semantic_workflow_state_event.tape",
            "visual_loop/screenshots/semantic_workflow_state_event_route.png",
            "visual_loop/screenshots/semantic_workflow_state_event_contract.png",
            "visual_loop/screenshots/semantic_workflow_state_event_inline.png",
            "visual_loop/screenshots/semantic_workflow_state_event_detail.png",
            "visual_loop/screenshots/semantic_workflow_state_event_final.png",
            "visual_loop/tapes/semantic_blocker_handoff.tape",
            "visual_loop/screenshots/semantic_blocker_handoff_inline.png",
            "visual_loop/screenshots/semantic_blocker_handoff_detail.png",
            "visual_loop/screenshots/semantic_blocker_handoff_final.png",
            "visual_loop/tapes/semantic_provider_failure_event.tape",
            "visual_loop/screenshots/semantic_provider_failure_inline.png",
            "visual_loop/screenshots/semantic_provider_failure_detail.png",
            "visual_loop/tapes/semantic_trace_revisit_stability.tape",
            "visual_loop/screenshots/semantic_trace_revisit_before.png",
            "visual_loop/screenshots/semantic_trace_revisit_other_session.png",
            "visual_loop/screenshots/semantic_trace_revisit_after.png",
            "visual_loop/tapes/semantic_redacted_tool_args.tape",
            "visual_loop/screenshots/semantic_redacted_tool_args_started.png",
            "visual_loop/screenshots/semantic_redacted_tool_args_completed.png",
            "visual_loop/screenshots/semantic_redacted_tool_args_detail.png",
        ),
    ),
    CorpusGroup(
        name="sidebars_context_files",
        description="sidebar modules, right-sidebar context/files, and layout editor",
        required=(
            "visual_loop/tapes/agents_files_sidebar.tape",
            "visual_loop/screenshots/agents_files_sidebar.png",
            "visual_loop/tapes/semantic_sidebar_layout_editor.tape",
            "visual_loop/screenshots/semantic_sidebar_layout_editor_default.png",
            "visual_loop/screenshots/semantic_sidebar_layout_editor_available.png",
            "visual_loop/screenshots/semantic_sidebar_layout_editor_right.png",
            "visual_loop/tapes/semantic_sidebar_layout_settings.tape",
            "visual_loop/screenshots/semantic_sidebar_layout_settings.png",
            "visual_loop/tapes/semantic_right_sidebar_layout.tape",
            "visual_loop/screenshots/semantic_right_sidebar_layout.png",
            "visual_loop/tapes/semantic_file_viewer_module.tape",
            "visual_loop/screenshots/semantic_file_viewer_module_initial.png",
            "visual_loop/screenshots/semantic_file_viewer_module_expanded.png",
            "visual_loop/screenshots/semantic_file_viewer_module_detail.png",
            "visual_loop/screenshots/semantic_file_viewer_module_raw.png",
            "visual_loop/screenshots/semantic_file_viewer_module_upload.png",
            "visual_loop/screenshots/file_detail_renderer_performance.report.md",
            "visual_loop/tapes/semantic_context_detail.tape",
            "visual_loop/screenshots/semantic_context_row_selected.png",
            "visual_loop/screenshots/semantic_context_detail.png",
            "visual_loop/tapes/semantic_file_picker.tape",
            "visual_loop/screenshots/semantic_file_picker.png",
            "visual_loop/screenshots/semantic_file_picker_tree_expanded.png",
            "visual_loop/tapes/agent_runtime_sidebar.tape",
            "visual_loop/screenshots/agent_runtime_sidebar.png",
        ),
    ),
    CorpusGroup(
        name="settings_provider",
        description="settings tabs, provider setup, and white-background modal smoke",
        required=(
            "visual_loop/tapes/semantic_settings_lists.tape",
            "visual_loop/screenshots/semantic_settings_agent.png",
            "visual_loop/tapes/semantic_settings_agent_compact.tape",
            "visual_loop/screenshots/semantic_settings_agent_compact.png",
            "visual_loop/tapes/semantic_settings_agent_long.tape",
            "visual_loop/screenshots/semantic_settings_agent_long_top.png",
            "visual_loop/screenshots/semantic_settings_agent_long_scrolled.png",
            "visual_loop/screenshots/semantic_settings_agent_long_detail.png",
            "visual_loop/screenshots/semantic_settings_theme.png",
            "visual_loop/screenshots/semantic_settings_tui.png",
            "visual_loop/screenshots/semantic_settings_language.png",
            "visual_loop/tapes/semantic_provider_setup.tape",
            "visual_loop/screenshots/semantic_provider_setup.png",
            "visual_loop/screenshots/semantic_provider_setup_provider_changed.png",
            "visual_loop/tapes/semantic_provider_edge_states.tape",
            "visual_loop/screenshots/semantic_provider_edge_catalog.png",
            "visual_loop/screenshots/semantic_provider_edge_auth_required.png",
            "visual_loop/screenshots/semantic_provider_edge_auth_failure.png",
            "visual_loop/tapes/semantic_provider_auth_success.tape",
            "visual_loop/screenshots/semantic_provider_auth_success_before.png",
            "visual_loop/screenshots/semantic_provider_auth_success_after.png",
            "visual_loop/tapes/semantic_theme_cycle.tape",
            "visual_loop/screenshots/semantic_theme_cycle_before.png",
            "visual_loop/screenshots/semantic_theme_cycle_next.png",
            "visual_loop/screenshots/semantic_theme_cycle_prev.png",
            "visual_loop/tapes/semantic_narrow_deep_modals.tape",
            "visual_loop/screenshots/semantic_narrow_settings.png",
            "visual_loop/screenshots/semantic_narrow_provider_setup.png",
            "visual_loop/tapes/white_modal_smoke.tape",
            "visual_loop/screenshots/white_modal_smoke_base.png",
            "visual_loop/screenshots/white_modal_smoke_settings.png",
            "visual_loop/screenshots/white_modal_smoke_help.png",
            "visual_loop/screenshots/white_modal_smoke_palette.png",
            "visual_loop/tapes/white_provider_setup.tape",
            "visual_loop/screenshots/white_provider_setup.png",
        ),
    ),
    CorpusGroup(
        name="shared_menu_surfaces",
        description="help, settings, metrics, tools, and doctor shared modal/menu proof",
        required=(
            "visual_loop/tapes/semantic_header_actions.tape",
            "visual_loop/screenshots/semantic_header_actions_base.png",
            "visual_loop/screenshots/semantic_header_actions_help.png",
            "visual_loop/screenshots/semantic_header_actions_settings.png",
            "visual_loop/tapes/semantic_menu_smoke.tape",
            "visual_loop/screenshots/semantic_menu_help_commands.png",
            "visual_loop/screenshots/semantic_menu_settings_tui.png",
            "visual_loop/screenshots/semantic_menu_metrics.png",
            "visual_loop/screenshots/semantic_menu_tools_catalog.png",
            "visual_loop/screenshots/semantic_menu_tool_detail.png",
            "visual_loop/screenshots/semantic_menu_doctor_health.png",
            "visual_loop/screenshots/semantic_menu_doctor_capabilities.png",
            "visual_loop/tapes/semantic_doctor_gaps.tape",
            "visual_loop/screenshots/semantic_doctor_gaps.png",
            "visual_loop/screenshots/semantic_narrow_metrics.png",
            "visual_loop/screenshots/gact_diag_clipboard_terminal.report.md",
            "visual_loop/screenshots/diagnostics_readiness.report.md",
        ),
    ),
    CorpusGroup(
        name="questions_retry_permissions",
        description="ask-user, retry, permissions, text-entry, and action modals",
        required=(
            "visual_loop/tapes/issue57_ask_user_retry.tape",
            "visual_loop/screenshots/issue57_ask_user_retry.png",
            "visual_loop/screenshots/issue57_ask_user_answer_modal.png",
            "visual_loop/screenshots/issue57_retry_model_modal.png",
            "visual_loop/screenshots/issue57_retry_notes_modal.png",
            "visual_loop/tapes/semantic_text_entry_modals.tape",
            "visual_loop/screenshots/semantic_rename_modal.png",
            "visual_loop/screenshots/semantic_context_add_modal.png",
            "visual_loop/tapes/semantic_compose_modal.tape",
            "visual_loop/screenshots/semantic_compose_modal.png",
            "visual_loop/tapes/semantic_permissions_inspector.tape",
            "visual_loop/screenshots/semantic_permissions_inspector.png",
            "visual_loop/tapes/semantic_sidebar_footer_actions.tape",
            "visual_loop/screenshots/semantic_sidebar_footer_actions.png",
            "visual_loop/tapes/semantic_conversation_actions.tape",
            "visual_loop/screenshots/semantic_conversation_actions.png",
        ),
    ),
    CorpusGroup(
        name="semantic_interactions",
        description="palette, workspace, MCP, memory, startup, permission, and action-menu proof",
        required=(
            "visual_loop/tapes/semantic_palette.tape",
            "visual_loop/screenshots/semantic_palette_commands.png",
            "visual_loop/screenshots/semantic_palette_search.png",
            "visual_loop/tapes/semantic_permission_banner.tape",
            "visual_loop/screenshots/semantic_permission_banner.png",
            "visual_loop/tapes/semantic_startup_intro.tape",
            "visual_loop/screenshots/semantic_startup_intro.png",
            "visual_loop/tapes/semantic_startup_connecting.tape",
            "visual_loop/screenshots/semantic_startup_connecting.png",
            "visual_loop/tapes/semantic_startup_error.tape",
            "visual_loop/screenshots/semantic_startup_error.png",
            "visual_loop/tapes/semantic_workspace_switch.tape",
            "visual_loop/screenshots/semantic_workspace_header_root.png",
            "visual_loop/screenshots/semantic_workspace_switch.png",
            "visual_loop/screenshots/semantic_workspace_create_form.png",
            "visual_loop/tapes/semantic_mcp_install.tape",
            "visual_loop/screenshots/semantic_mcp_install.png",
            "visual_loop/tapes/semantic_mcp_remove.tape",
            "visual_loop/screenshots/semantic_mcp_remove.png",
            "visual_loop/tapes/semantic_tools_mcp_catalog.tape",
            "visual_loop/screenshots/semantic_tools_mcp_catalog.png",
            "visual_loop/screenshots/semantic_tools_mcp_tool_selected.png",
            "visual_loop/tapes/semantic_tools_action_detail.tape",
            "visual_loop/screenshots/semantic_tools_action_detail_catalog.png",
            "visual_loop/screenshots/semantic_tools_action_detail_builtin.png",
            "visual_loop/tapes/semantic_tools_mcp_disconnected.tape",
            "visual_loop/screenshots/semantic_tools_mcp_disconnected_catalog.png",
            "visual_loop/screenshots/semantic_tools_mcp_disconnected_selected.png",
            "visual_loop/tapes/semantic_tools_mcp_reconnect_failure.tape",
            "visual_loop/screenshots/semantic_tools_mcp_reconnect_failure.png",
            "visual_loop/tapes/semantic_tools_unavailable_tool.tape",
            "visual_loop/screenshots/semantic_tools_unavailable_tool.png",
            "visual_loop/tapes/semantic_tools_empty.tape",
            "visual_loop/screenshots/semantic_tools_empty.png",
            "visual_loop/screenshots/semantic_narrow_tools_mcp.png",
            "visual_loop/tapes/semantic_context_actions.tape",
            "visual_loop/screenshots/semantic_context_actions.png",
            "visual_loop/tapes/semantic_diff_actions.tape",
            "visual_loop/screenshots/semantic_diff_actions.png",
            "visual_loop/tapes/semantic_session_actions.tape",
            "visual_loop/screenshots/semantic_session_actions.png",
            "visual_loop/tapes/semantic_memory_inspector.tape",
            "visual_loop/screenshots/semantic_memory_palette.png",
            "visual_loop/screenshots/semantic_memory_inspector.png",
            "visual_loop/tapes/semantic_prompt_catalog.tape",
            "visual_loop/screenshots/semantic_prompt_catalog.png",
            "visual_loop/screenshots/semantic_prompt_profiles.png",
            "visual_loop/screenshots/semantic_prompt_detail.png",
            "visual_loop/screenshots/semantic_prompt_editor.png",
            "visual_loop/screenshots/semantic_prompt_saved.png",
            "visual_loop/tapes/semantic_prompt_empty.tape",
            "visual_loop/screenshots/semantic_prompt_empty.png",
            "visual_loop/tapes/semantic_prompt_catalog_stress.tape",
            "visual_loop/screenshots/semantic_prompt_stress_catalog.png",
            "visual_loop/screenshots/semantic_prompt_stress_invalid_detail.png",
            "visual_loop/screenshots/semantic_prompt_stress_validation_render.png",
            "visual_loop/screenshots/semantic_prompt_stress_save_editor.png",
            "visual_loop/screenshots/semantic_prompt_stress_save_failure.png",
            "visual_loop/screenshots/semantic_narrow_prompts.png",
            "visual_loop/screenshots/semantic_narrow_prompt_detail.png",
            "visual_loop/tapes/semantic_expert_packs.tape",
            "visual_loop/screenshots/semantic_expert_packs_catalog.png",
            "visual_loop/screenshots/semantic_expert_packs_detail.png",
            "visual_loop/tapes/semantic_expert_packs_empty.tape",
            "visual_loop/screenshots/semantic_expert_packs_empty.png",
            "visual_loop/tapes/semantic_expert_packs_stress.tape",
            "visual_loop/screenshots/semantic_expert_packs_stress_catalog.png",
            "visual_loop/screenshots/semantic_expert_packs_stress_detail.png",
            "visual_loop/screenshots/semantic_expert_packs_source_provenance.png",
            "visual_loop/screenshots/semantic_expert_packs_update_failure.png",
            "visual_loop/screenshots/semantic_expert_packs_delete_confirm.png",
            "visual_loop/screenshots/semantic_expert_packs_delete_failure.png",
            "visual_loop/tapes/semantic_expert_packs_install_failure.tape",
            "visual_loop/screenshots/semantic_expert_packs_install_source.png",
            "visual_loop/screenshots/semantic_expert_packs_install_failure.png",
            "visual_loop/screenshots/semantic_narrow_expert_packs.png",
            "visual_loop/screenshots/semantic_narrow_expert_pack_detail.png",
            "visual_loop/tapes/semantic_sidebar_filter.tape",
            "visual_loop/screenshots/semantic_sidebar_filter.png",
            "visual_loop/tapes/semantic_quit_confirm.tape",
            "visual_loop/screenshots/semantic_quit_confirm.png",
        ),
    ),
    CorpusGroup(
        name="marketplace_blueprints",
        description="Agent Blueprint marketplace, source provenance, validation, and lifecycle proof",
        required=(
            "visual_loop/tapes/semantic_agent_blueprint_active_marker.tape",
            "visual_loop/screenshots/semantic_agent_blueprint_active_marker_catalog.png",
            "visual_loop/screenshots/semantic_agent_blueprint_active_marker_detail.png",
            "visual_loop/tapes/semantic_agent_blueprint_management.tape",
            "visual_loop/screenshots/semantic_agent_blueprint_management_catalog.png",
            "visual_loop/screenshots/semantic_agent_blueprint_management_install.png",
            "visual_loop/screenshots/semantic_agent_blueprint_management_installed.png",
            "visual_loop/screenshots/semantic_agent_blueprint_management_validate.png",
            "visual_loop/screenshots/semantic_agent_blueprint_management_validation_detail.png",
            "visual_loop/screenshots/semantic_agent_blueprint_management_builtin_detail.png",
            "visual_loop/screenshots/semantic_agent_blueprint_management_workspace_detail.png",
            "visual_loop/screenshots/semantic_agent_blueprint_management_delete_confirm.png",
            "visual_loop/screenshots/semantic_agent_blueprint_management_updated.png",
            "visual_loop/tapes/semantic_agent_blueprint_sources.tape",
            "visual_loop/screenshots/semantic_agent_blueprint_sources_catalog.png",
            "visual_loop/screenshots/semantic_agent_blueprint_sources_registry.png",
            "visual_loop/screenshots/semantic_agent_blueprint_sources_add_source.png",
            "visual_loop/screenshots/semantic_agent_blueprint_sources_added.png",
            "visual_loop/screenshots/semantic_agent_blueprint_sources_remove_confirm.png",
            "visual_loop/screenshots/semantic_agent_blueprint_sources_install_row.png",
            "visual_loop/screenshots/semantic_agent_blueprint_sources_installed.png",
            "visual_loop/screenshots/semantic_agent_blueprint_sources_detail.png",
            "visual_loop/tapes/semantic_agent_blueprint_failures.tape",
            "visual_loop/screenshots/semantic_agent_blueprint_validation_warning.png",
            "visual_loop/screenshots/semantic_agent_blueprint_validation_error.png",
            "visual_loop/screenshots/semantic_agent_blueprint_install_failure.png",
            "visual_loop/screenshots/semantic_agent_blueprint_update_failure.png",
            "visual_loop/screenshots/semantic_agent_blueprint_delete_failure.png",
            "visual_loop/screenshots/semantic_agent_blueprint_source_refresh_failure.png",
            "visual_loop/tapes/semantic_agent_blueprint_tree_stress.tape",
            "visual_loop/screenshots/semantic_agent_blueprint_tree_stress_catalog.png",
            "visual_loop/screenshots/semantic_agent_blueprint_tree_stress_detail.png",
            "visual_loop/screenshots/semantic_agent_blueprint_tree_stress_sources.png",
            "visual_loop/tapes/semantic_agent_blueprint_tree_stress_narrow.tape",
            "visual_loop/screenshots/semantic_agent_blueprint_tree_stress_narrow_catalog.png",
            "visual_loop/screenshots/semantic_agent_blueprint_tree_stress_narrow_detail.png",
            "visual_loop/tapes/codex_blueprint_catalog_uiux.tape",
            "visual_loop/screenshots/codex_blueprint_catalog_uiux.png",
            "visual_loop/tapes/semantic_agent_blueprint_commands.tape",
            "visual_loop/screenshots/semantic_agent_blueprint_commands_palette.png",
            "visual_loop/tapes/semantic_agent_management.tape",
            "visual_loop/screenshots/semantic_agent_management_catalog.png",
            "visual_loop/screenshots/semantic_agent_management_create.png",
            "visual_loop/screenshots/semantic_agent_management_extract.png",
            "visual_loop/screenshots/semantic_agent_management_detail.png",
            "visual_loop/screenshots/semantic_agent_management_clone.png",
            "visual_loop/screenshots/semantic_agent_management_cloned.png",
            "visual_loop/screenshots/semantic_agent_management_edit.png",
            "visual_loop/screenshots/semantic_agent_management_updated.png",
            "visual_loop/screenshots/semantic_agent_management_deleted.png",
        ),
    ),
    CorpusGroup(
        name="benchmark_live_replay",
        description="persisted CLIO/ALCF benchmark replay screenshots",
        required=(
            "visual_loop/tapes/live_clio_ndp.tape",
            "visual_loop/screenshots/live_clio_ndp_bottom.png",
            "visual_loop/screenshots/live_clio_ndp_after_pagedown.png",
            "visual_loop/screenshots/live_clio_ndp_after_end.png",
            "visual_loop/screenshots/live_clio_ndp_tool_detail.png",
            "visual_loop/tapes/live_clio_ndp_top.tape",
            "visual_loop/screenshots/live_clio_ndp_top.png",
            "visual_loop/screenshots/live_clio_ndp_tool_selection.png",
            "visual_loop/tapes/live_clio_nanoagents.tape",
            "visual_loop/screenshots/live_clio_nanoagents_collapsed.png",
            "visual_loop/screenshots/live_clio_nanoagents_expanded.png",
            "visual_loop/screenshots/live_clio_nanoagent_child_open.png",
            "visual_loop/tapes/live_clio_catalogs.tape",
            "visual_loop/screenshots/live_clio_agents_catalog.png",
            "visual_loop/screenshots/live_clio_agent_detail.png",
            "visual_loop/screenshots/live_clio_tools_catalog.png",
            "visual_loop/screenshots/live_clio_tool_catalog_detail.png",
            "visual_loop/screenshots/live_clio_mcp_catalog.png",
            "visual_loop/screenshots/live_clio_mcp_detail.png",
            "visual_loop/tapes/live_clio_catalogs_narrow.tape",
            "visual_loop/screenshots/live_clio_tools_catalog_narrow.png",
            "visual_loop/screenshots/live_clio_tool_detail_narrow.png",
            "visual_loop/tapes/live_clio_memory.tape",
            "visual_loop/screenshots/live_clio_memory_palette.png",
            "visual_loop/screenshots/live_clio_memory_inspector.png",
            "visual_loop/tapes/live_clio_memory_pressure.tape",
            "visual_loop/screenshots/live_clio_memory_pressure.png",
            "visual_loop/tapes/live_clio_artifacts.tape",
            "visual_loop/screenshots/live_clio_artifact_transcript.png",
            "visual_loop/screenshots/live_clio_artifact_detail.png",
            "visual_loop/tapes/live_clio_compaction.tape",
            "visual_loop/screenshots/live_clio_compaction_top.png",
            "visual_loop/screenshots/live_clio_compaction_detail.png",
            "visual_loop/screenshots/live_clio_compaction_bottom.png",
            "visual_loop/tapes/live_clio_state_markers.tape",
            "visual_loop/screenshots/live_clio_provider_swap_top.png",
            "visual_loop/screenshots/live_clio_provider_swap_bottom.png",
            "visual_loop/tapes/live_clio_sidebar_errors.tape",
            "visual_loop/screenshots/live_clio_error_session.png",
            "visual_loop/screenshots/live_clio_error_detail.png",
            "visual_loop/tapes/live_clio_provenance_detail.tape",
            "visual_loop/screenshots/live_clio_provenance_selection.png",
            "visual_loop/screenshots/live_clio_provenance_detail.png",
        ),
    ),
    CorpusGroup(
        name="remote_alcf_replay",
        description="persisted ALCF provider-swap and sidebar-section replay proof",
        required=(
            "visual_loop/tapes/live_alcf_20260525_provider_swap.tape",
            "visual_loop/screenshots/live_alcf_20260525_provider_swap_top.png",
            "visual_loop/screenshots/live_alcf_20260525_provider_swap_bottom.png",
            "visual_loop/tapes/live_alcf_20260525_sidebar_sections.tape",
            "visual_loop/screenshots/live_alcf_20260525_sidebar_sessions_header_focused.png",
            "visual_loop/screenshots/live_alcf_20260525_sidebar_sessions_collapsed.png",
            "visual_loop/screenshots/live_alcf_20260525_sidebar_context_focused.png",
            "visual_loop/screenshots/live_alcf_20260525_sidebar_sections_collapsed.png",
            "visual_loop/screenshots/live_alcf_20260525_sidebar_sections_expanded.png",
        ),
    ),
    CorpusGroup(
        name="temporal_observability",
        description="JSONL/report gates for live semantic streaming and operator diagnostics",
        required=(
            "visual_loop/assert_live_observability.py",
            "visual_loop/test_assert_live_observability.py",
            "visual_loop/capture_live_observability.py",
            "visual_loop/capture_tui_mouse_latency_pty.py",
            "visual_loop/check_tui_latency_readiness.py",
            "visual_loop/screenshots/gact_diag_clipboard_terminal.report.md",
            "visual_loop/screenshots/diagnostics_readiness.report.md",
            "visual_loop/screenshots/tui_latency_readiness.report.md",
            "visual_loop/screenshots/tui_mouse_latency_pty_manifest.json",
            "visual_loop/screenshots/tui_mouse_latency_pty_report.json",
            "visual_loop/screenshots/live_observability_20260601_131300.jsonl",
            "visual_loop/screenshots/live_observability_20260601_131300.report.md",
            "visual_loop/screenshots/live_observability_20260601_131300.strict.report.md",
            "visual_loop/screenshots/live_observability_clio_semantic_live_events.jsonl",
            "visual_loop/screenshots/live_observability_clio_semantic_live_events.report.md",
            "visual_loop/screenshots/live_observability_clio_semantic_live_events.strict.report.md",
        ),
    ),
)
