#requires -Version 5.1
<#
.SYNOPSIS
  PowerShell counterpart to fetch-sidecar.sh for Windows CI / local dev.

.DESCRIPTION
  Builds the sidecar launcher binary for the host triple (or requested
  triples) and drops it under apps/desktop/src-tauri/binaries/. Also
  writes sidecar.lock with the resolved clio-agent-gact path on the
  build host.

.PARAMETER All
  Build every supported target triple.

.PARAMETER Triples
  Specific triples to build (e.g. "x86_64-pc-windows-msvc").
#>
[CmdletBinding()]
param(
  [switch] $All,
  [string[]] $Triples
)

$ErrorActionPreference = 'Stop'

$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$src  = Join-Path $root 'sidecar-launcher'
$out  = Join-Path $root 'src-tauri\binaries'
$lock = Join-Path $root 'src-tauri\sidecar.lock'

if (-not (Test-Path $out)) { New-Item -ItemType Directory -Path $out | Out-Null }

$targets = @{
  'x86_64-pc-windows-msvc'   = @{ GOOS='windows'; GOARCH='amd64'; ext='.exe' }
  'aarch64-apple-darwin'     = @{ GOOS='darwin';  GOARCH='arm64'; ext=''     }
  'x86_64-apple-darwin'      = @{ GOOS='darwin';  GOARCH='amd64'; ext=''     }
  'x86_64-unknown-linux-gnu' = @{ GOOS='linux';   GOARCH='amd64'; ext=''     }
}

function Get-HostTriple { 'x86_64-pc-windows-msvc' }

function Build-One($triple) {
  if (-not $targets.ContainsKey($triple)) {
    throw "fetch-sidecar: unknown target triple: $triple"
  }
  $t = $targets[$triple]
  $outFile = Join-Path $out "clio-agent-$triple$($t.ext)"
  Write-Host "[fetch-sidecar] building $triple -> $outFile"
  Push-Location $src
  try {
    $env:GOWORK = 'off'
    $env:GOOS = $t.GOOS
    $env:GOARCH = $t.GOARCH
    $env:CGO_ENABLED = '0'
    & go build -trimpath -ldflags='-s -w' -o $outFile .
    if ($LASTEXITCODE -ne 0) { throw "go build failed for $triple (exit $LASTEXITCODE)" }
  } finally {
    Pop-Location
    Remove-Item Env:\GOWORK -ErrorAction SilentlyContinue
    Remove-Item Env:\GOOS -ErrorAction SilentlyContinue
    Remove-Item Env:\GOARCH -ErrorAction SilentlyContinue
    Remove-Item Env:\CGO_ENABLED -ErrorAction SilentlyContinue
  }
}

function Resolve-GactBin {
  if ($env:CLIO_AGENT_GACT_BIN -and (Test-Path $env:CLIO_AGENT_GACT_BIN)) {
    return $env:CLIO_AGENT_GACT_BIN
  }
  $cmd = Get-Command clio-agent-gact -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  $localApp = $env:LOCALAPPDATA
  if (-not $localApp) { $localApp = Join-Path $env:USERPROFILE 'AppData\Local' }
  $p = Join-Path $localApp 'clio\clio-agent\.venv\Scripts\clio-agent-gact.exe'
  if (Test-Path $p) { return $p }
  $devp = 'D:\Libraries\Documents\projects\clio-agent\.venv\Scripts\clio-agent-gact.exe'
  if (Test-Path $devp) { return $devp }
  return ''
}

function Write-Lock($resolved) {
  $now = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
  $hostTriple = Get-HostTriple
  $body = @"
# Generated by apps/desktop/scripts/fetch-sidecar.ps1 — do not hand-edit.
#
# This file pins the sidecar resolution context for reproducibility.
# The launcher binary in apps/desktop/src-tauri/binaries/ executes the
# clio-agent-gact server at runtime; this lockfile records what was
# discoverable on the build host so reviewers can see whether the
# build is bound to a system install or a fresh develop checkout.

generated_at = "$now"
host_triple = "$hostTriple"
resolved_clio_agent_gact = "$resolved"
contract = "GACT v0.2"
source_branch = "develop"
source_repo = "https://github.com/iowarp/clio-agent"
install_recipe = "CLIO_REF=develop curl -fsSL https://raw.githubusercontent.com/iowarp/clio-agent/main/install/install.sh | bash"
windows_install_recipe = '`$env:CLIO_REF = ''develop''; irm https://raw.githubusercontent.com/iowarp/clio-agent/main/install/install.ps1 | iex'
"@
  Set-Content -LiteralPath $lock -Value $body -Encoding utf8
}

$wanted = @()
if ($All) {
  $wanted = $targets.Keys
} elseif ($Triples -and $Triples.Count -gt 0) {
  $wanted = $Triples
} else {
  $wanted = @(Get-HostTriple)
}

foreach ($t in $wanted) { Build-One $t }

$resolved = Resolve-GactBin
Write-Lock $resolved
if (-not $resolved) {
  Write-Warning "clio-agent-gact not resolved on this host. The launcher will resolve at runtime; install clio-agent@develop via the upstream installer."
} else {
  Write-Host "[fetch-sidecar] resolved clio-agent-gact: $resolved"
}
