import { expect, test } from '@playwright/test';

const endpoint = `http://127.0.0.1:${process.env['CLIO_FIXTURE_PORT'] ?? '18799'}`;

test('keeps response preparation in the transcript and showcases beside the canvas opener', async ({
  page,
}) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  expect((await page.request.post(`${endpoint}/__test/reset`)).ok()).toBe(true);
  await page.request.post(`${endpoint}/v1/permissions/perm_fixture`);
  await page.request.post(
    `${endpoint}/v1/sessions/sess_flat_ndp/questions/question_fixture/answer`,
    {
      data: { selected_options: ['table'] },
    },
  );
  await page.addInitScript((value) => {
    localStorage.setItem('clio.recent-connections', JSON.stringify([value]));
    localStorage.setItem('theme', 'light');
  }, endpoint);
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.goto('/workspaces/ws_flat_ndp/sessions/sess_flat_ndp');
  const composer = page.locator('[data-slot="clio-composer-stack"]');
  const activity = page.getByRole('button', { name: /^Evidence layout:/ });
  await expect(activity).toBeVisible();
  const header = page.locator('[data-slot="workspace-header"]');
  await expect(header.getByRole('button', { name: /^Evidence layout:/ })).toBeVisible();
  await expect(composer.getByRole('button', { name: /^Evidence layout:/ })).toHaveCount(0);
  await expect(activity.locator('xpath=../following-sibling::button')).toHaveAttribute(
    'aria-label',
    'Open workspace canvas',
  );
  await expect(composer.getByText('Working on your request')).toHaveCount(0);
  await expect(composer.getByText('Session details')).toHaveCount(0);
  await page.request.post(`${endpoint}/__test/prepare-turn`, { data: { phase: 'start' } });
  const preparation = page.locator('[data-slot="turn-preparation"]');
  await expect(preparation).toHaveText('Preparing next response');
  await expect(
    page.getByRole('log', { name: 'Conversation' }).locator('[data-slot="turn-preparation"]'),
  ).toBeVisible();
  await expect(composer.locator('[data-slot="turn-preparation"]')).toHaveCount(0);
  const preparationComposer = await composer.boundingBox();
  await page.request.post(`${endpoint}/__test/prepare-turn`, { data: { phase: 'token' } });
  await expect(preparation).toHaveCount(0);
  expect(await composer.boundingBox()).toEqual(preparationComposer);

  for (const width of [1920, 1280, 390]) {
    await page.setViewportSize({ width, height: 900 });
    await expect(activity).toBeVisible();
    const input = composer.locator('[contenteditable="true"]');
    await input.fill('Keep this draft while I review the evidence.');
    const before = await composer.boundingBox();
    await activity.click();
    await activity.click();
    await activity.click();
    const panel = page.getByRole('dialog', { name: 'Activity and evidence' });
    await expect(panel).toBeVisible();
    const top = panel.locator('[data-showcase-section="top"]');
    const bottom = panel.locator('[data-showcase-section="bottom"]');
    const details = panel.getByRole('button', { name: 'Open full details' });
    await expect(
      panel
        .locator('[data-slot="session-summary-header"]')
        .getByRole('button', { name: 'Open full details' }),
    ).toBeVisible();
    await expect(details).toHaveText('');
    await expect(panel.getByText('Output', { exact: true })).toHaveCount(0);
    await expect(panel.locator('[data-slot="artifact"]')).toHaveCount(0);
    await expect(top.getByRole('button', { name: 'Artifacts, 1 recorded' })).toBeVisible();
    await expect(bottom.getByRole('button', { name: 'Artifacts, 1 recorded' })).toHaveCount(0);
    await expect(top.getByRole('button', { name: /^Tool calls/ })).toHaveCount(0);
    await expect(panel.getByText('Progress and outputs', { exact: true })).toHaveCount(0);
    await expect(panel.getByText('Used in this session', { exact: true })).toHaveCount(0);
    await expect(panel.getByText(/^Generated by/)).toHaveCount(0);
    await expect(panel.getByText('Connected sources could not be loaded.')).toHaveCount(0);
    const bounds = await panel.boundingBox();
    expect(await panel.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true);
    for (const row of await panel.locator('.group\\/artifact').all()) {
      expect(await row.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true);
    }
    expect(bounds!.x).toBeGreaterThanOrEqual(0);
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width);
    const form = await composer.locator('form').boundingBox();
    if (width === 1920) {
      await expect(panel).toHaveAttribute('data-showcase-mode', 'docked');
      const column = await page.locator('[data-slot="transcript-column"]').boundingBox();
      expect(bounds!.x).toBeGreaterThan(column!.x + column!.width);
      expect(bounds!.x).toBeGreaterThan(form!.x + form!.width);
    } else {
      await expect(panel).toHaveAttribute('data-showcase-mode', 'temporary');
      const toggle = await activity.boundingBox();
      expect(bounds!.y).toBeGreaterThanOrEqual(toggle!.y + toggle!.height);
      expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(form!.y);
    }
    await panel.getByRole('button', { name: 'Hide activity and evidence' }).click();
    await expect(panel).toHaveCount(0);
    await expect(activity).toBeFocused();
    expect(await composer.boundingBox()).toEqual(before);
    await expect(input).toContainText('Keep this draft while I review the evidence.');
    expect(await composer.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true);
    await activity.click({ button: 'right' });
    await expect(activity).toHaveAttribute('data-evidence-layout', 'both');
    await panel.evaluate(async (node) => {
      await Promise.all(node.getAnimations().map((animation) => animation.finished));
    });
    const both = await panel.boundingBox();
    await activity.click({ button: 'right' });
    await expect(activity).toHaveAttribute('data-evidence-layout', 'top');
    expect(await panel.boundingBox()).toEqual(both);
    await expect(panel.locator('[data-showcase-section="bottom"]')).toHaveCount(0);
    await activity.click({ button: 'right' });
    await expect(activity).toHaveAttribute('data-evidence-layout', 'bottom');
    expect(await panel.boundingBox()).toEqual(both);
    await expect(panel.getByRole('button', { name: 'Artifacts, 1 recorded' })).toHaveCount(0);
    await activity.click({ button: 'right' });
    await expect(activity).toHaveAttribute('data-evidence-layout', 'none');
    await expect(panel).toHaveCount(0);
    await activity.click();
    await input.click();
    if (width === 1920) {
      await expect(panel).toBeVisible();
      await panel.getByRole('button', { name: 'Hide activity and evidence' }).click();
    } else {
      await expect(panel).toHaveCount(0);
    }
    await input.click();
    await expect(input).toBeFocused();
    await activity.click();
    await page.keyboard.press('Escape');
    await expect(panel).toHaveCount(0);
    await page.keyboard.press('ArrowRight');
    await expect(activity).toHaveAttribute('data-evidence-layout', 'bottom');
    await page.keyboard.press('ArrowLeft');
    await expect(activity).toHaveAttribute('data-evidence-layout', 'none');
  }
  await page.setViewportSize({ width: 1920, height: 900 });
  await activity.click({ button: 'right' });
  await expect(page.getByRole('dialog', { name: 'Activity and evidence' })).toHaveAttribute(
    'data-showcase-mode',
    'docked',
  );
  await page.setViewportSize({ width: 1280, height: 900 });
  await expect(page.getByRole('dialog', { name: 'Activity and evidence' })).toHaveCount(0);
  await expect(activity).toHaveAttribute('data-evidence-layout', 'none');
  expect(errors).toEqual([]);
});
