package scenario

import "strings"

var longReplyVariants = []struct {
	thinking string
	body     string
}{
	{
		thinking: "The user wants a longform writeup. Let me lay it out in sections.\n",
		body:     longReplyText,
	},
	{
		thinking: "Architecture question. I'll trace the request path end-to-end.\n",
		body:     longArchitectureWriteup,
	},
	{
		thinking: "Performance audit. Let me walk through the hot paths I'd profile first.\n",
		body:     longPerfWriteup,
	},
}

// longArchitectureWriteup is the second long-reply variant — a
// request-path trace through a hypothetical service.
var longArchitectureWriteup = strings.Join([]string{
	"## Request lifecycle",
	"",
	"From the moment a request hits the load balancer to the moment the",
	"response is serialized back, here's what runs and in what order.",
	"",
	"## 1. Edge",
	"",
	"The L7 load balancer terminates TLS, applies a basic WAF rule set, and",
	"routes by host header. /api/* lands on the API gateway pool; /static/*",
	"goes to the CDN origin. Connection reuse is on (HTTP/2 frontside,",
	"HTTP/1.1 keep-alive backside) so we don't pay handshake cost per call.",
	"",
	"## 2. API gateway",
	"",
	"The gateway adds three things the upstream services don't see:",
	"",
	"- **Rate limiting**: token bucket per (route, api_key). 429 leaves the",
	"  gateway without ever reaching the service.",
	"- **Request signing**: HMAC of (method, path, ts, body) added to the",
	"  request as `X-Sig`. Services validate before processing.",
	"- **Tracing**: w3c traceparent generated if absent; propagated otherwise.",
	"",
	"## 3. Service router",
	"",
	"Inside each service container, a router (chi-style) maps method+path to",
	"a handler. Middleware: auth (verify JWT, populate request context),",
	"audit (log request shape minus PII), rate limit (per-user backstop in",
	"case the gateway misses).",
	"",
	"## 4. Handler",
	"",
	"Handlers are intentionally thin — parse + validate input, call into the",
	"service layer, marshal the result. The service layer holds business",
	"logic and is testable without HTTP plumbing.",
	"",
	"## 5. Persistence",
	"",
	"The service layer talks to the data layer via a thin repository",
	"interface. Reads can hit the read replica; writes go to the primary.",
	"Caching sits between the repository and the database — Redis, with a",
	"30-second TTL on hot keys.",
	"",
	"## 6. Async fanout",
	"",
	"Side effects (outbound webhooks, ML feature recomputation, audit log",
	"shipping) are enqueued on Kafka topics from the service layer, then",
	"processed by dedicated worker pools. The handler doesn't wait.",
	"",
	"## 7. Response",
	"",
	"On the way back: the handler returns a typed result, the marshaller",
	"emits JSON, the gateway adds CORS + cache headers, the LB compresses",
	"if accept-encoding allows it. End-to-end p50 hovers around 18ms when",
	"the cache is warm.",
	"",
	"That's the full trace. Want me to drill into any one stage?",
}, "\n")

// longPerfWriteup is the third long-reply variant — a profiling
// triage memo.
var longPerfWriteup = strings.Join([]string{
	"## Profiling triage",
	"",
	"If the service is slow and you don't know why, walk these in order.",
	"Each step takes minutes; together they catch ~80% of perf bugs.",
	"",
	"## 1. CPU profile (pprof)",
	"",
	"Pull a 30s CPU profile from production at peak. Look for:",
	"",
	"- One function dominating the flame graph (>30% self-time). Usually",
	"  a regex compile inside a hot path, an unbounded JSON unmarshal, or",
	"  a serial loop that should fan out.",
	"- Allocator overhead (runtime.mallocgc) above ~15%. Means you're",
	"  thrashing the GC — pool the buffers, switch to value receivers, or",
	"  pre-size the slices.",
	"- Lock contention (sync.Mutex.Lock above ~10%). Indicates a single",
	"  shared structure that's serialising the request fleet.",
	"",
	"## 2. Heap profile",
	"",
	"After CPU, take a heap snapshot. Look for:",
	"",
	"- A single allocator above ~25% of in-use space. Usually a cache",
	"  with no eviction, a sync.Map without periodic compaction, or a",
	"  goroutine leak holding onto request-scoped buffers.",
	"- Allocation rate (alloc_objects) higher than necessary — same fix",
	"  set as CPU's allocator overhead.",
	"",
	"## 3. Trace (runtime/trace)",
	"",
	"Capture a 5s trace under load. Open in `go tool trace`. Look for:",
	"",
	"- GC pauses spanning many goroutines. If pause > 5ms regularly, see",
	"  heap. If pauses are rare but huge, you have a fragmentation issue.",
	"- Long stretches of single-goroutine work. Suggests serial code that",
	"  could parallelise (errgroup with bounded concurrency is the easy",
	"  fix).",
	"- Network I/O dominating the wallclock. Means the bottleneck is",
	"  downstream, not in your service.",
	"",
	"## 4. Database",
	"",
	"If the above didn't pin it, the bottleneck is probably the DB:",
	"",
	"- pg_stat_statements: top 5 queries by total_time. Almost always one",
	"  is missing an index or is a Cartesian product.",
	"- Connection pool exhaustion: if pool wait time > 0, you're under-",
	"  provisioned (or holding connections too long inside transactions).",
	"- Lock waits: pg_locks joined to pg_stat_activity. Long waits on a",
	"  shared row mean a hot key — shard the writes or batch them.",
	"",
	"## 5. Network",
	"",
	"Last resort, but cheap to check: sar -n DEV 1, look at retransmits.",
	"If high, the LB↔service path has a flaky link. Move the service or",
	"raise it with the network team — there's nothing to fix in code.",
	"",
	"That's the full profiling pass. Most outages get caught in the first",
	"two steps; the rest of the list is the long tail.",
}, "\n")

// SSSSSSSSS1: realistic payloads for multiToolVariants[0] — the
// original 2-line main.go was too shallow to demo the expand /
// per-part navigation flows. These are hand-written to feel like
// a real small Go service so the splash scenario gives the viewer
// something actually worth paging through.

// longReplyText is the payload for runLongScript — a multi-section
// writeup long enough to exercise compact-vs-dump rendering choices.
var longReplyText = strings.Join([]string{
	"## Overview",
	"",
	"This is a writeup spread across multiple sections so the renderer has a",
	"non-trivial amount of prose to deal with. Each paragraph is intentionally",
	"narrow so line wrapping kicks in at typical TUI widths.",
	"",
	"## Background",
	"",
	"The GACT contract (v0.1) defines a REST + SSE surface for agentic coders.",
	"Backends implement the surface; a single TUI drives any conforming",
	"backend. The emulator in this repo is the reference implementation;",
	"adapters in adapters/opencode and adapters/crush front real products.",
	"",
	"## Rendering concerns",
	"",
	"Long messages like this one need a rendering strategy that doesn't blow",
	"up the conversation pane. Three options:",
	"",
	"- **Dump**: render the full text inline. Works at small scale, degrades",
	"  fast as messages get long. Current behaviour.",
	"- **Truncate**: show the first N lines with a \"… more\" indicator. The",
	"  user doesn't learn anything about what's below without scrolling.",
	"- **Compact + detail**: render the first N lines inline, attach a key",
	"  binding that opens the full message in a floating detail window.",
	"  Matches how Crush renders big tool outputs. This is the direction",
	"  feedback L3 asks for.",
	"",
	"## Tool outputs",
	"",
	"The same problem applies to tool outputs — a 200-line log, a 50-line",
	"diff, even a verbose stderr trace. Whatever strategy we pick for long",
	"assistant text should also cover tool_result parts; otherwise the TUI",
	"renders inconsistently depending on the part type.",
	"",
	"## Prior art",
	"",
	"- Crush's conversation display: inline Bash(cmd) headers, leading `⎿`",
	"  for tool output, expand-on-focus for big blocks.",
	"- Claude Code: `Bash(…)` / `Write(…)` headers, `⎿` indented output,",
	"  fold-by-default behaviour for verbose commands.",
	"- OpenCode: inline full rendering + scroll-off. Less refined.",
	"",
	"## Proposal",
	"",
	"Match Claude Code's density: per-part headers that name the tool and a",
	"single-line preview of the input, leading `⎿` with the first few lines",
	"of output, a keybinding (likely Ctrl+Enter while the cursor is on the",
	"part) to open a floating detail pane.",
	"",
	"## Open questions",
	"",
	"1. Where does the body-level message cursor come from? The TUI doesn't",
	"   track one yet; K10's copy and K13's retry both cheat and target \"the",
	"   latest\".",
	"2. Does the floating detail pane scroll independently? Probably yes",
	"   for tool outputs, but that means wiring a second scroll offset.",
	"3. How do we expose the expand/collapse state across re-renders? State",
	"   lives on App, not on the parts themselves.",
	"",
	"That's the shape of the work. Ready to pick it up in the next iteration.",
}, "\n")

// bigLogOutput is a synthetic 80-ish-line log snippet used by
