/** Canonical GACT 0.3 state-bearing event vocabulary. */
export const GACT_V3_EVENT_TYPES = [
  'a2ui.surface.deleted',
  'a2ui.surface.upserted',
  'approval.resolved',
  'approval.upserted',
  'artifact.upserted',
  'infrastructure.dependency.changed',
  'message.block.completed',
  'message.block.delta',
  'message.block.upserted',
  'message.accepted',
  'message.cancelled',
  'message.completed',
  'message.upserted',
  'pending_steer.cancelled',
  'provider_catalog.refreshed',
  'question.upserted',
  'queued_message.created',
  'queued_message.deleted',
  'queued_message.promoted',
  'queued_message.promotion_failed',
  'queued_message.reordered',
  'queued_message.updated',
  'resource.created',
  'resource.deleted',
  'resource.delivery_resolved',
  'resource.processing_cancelled',
  'resource.processing_completed',
  'resource.processing_failed',
  'resource.processing_started',
  'resource.ready',
  'resource.upload_progress',
  'run.upserted',
  'session.upserted',
  'stream.gap',
  'stream.live',
  'subagent.upserted',
  'task.upserted',
  'tool.upserted',
  'workspace.upserted',
] as const;

export type GactV3EventType = (typeof GACT_V3_EVENT_TYPES)[number];
