/**
 * Assembles the ChatLayout's derived view state and wires its many sub-models
 * (selection, UI state, services) into a single layout context.
 */
import { createChatLayoutCommandWiring } from './chatLayoutCommandWiring.js';
import { createChatLayoutDerivedState } from './chatLayoutDerivedState.js';
import { createChatLayoutServices } from './chatLayoutServices.js';
import { createChatLayoutUiState } from './chatLayoutUiState.js';
import type { ChatLayoutProps } from './ChatLayoutTypes.js';

export function createChatLayoutModel(props: ChatLayoutProps) {
  const {
    activeDiff,
    setActiveDiff,
    paletteOpen,
    setPaletteOpen,
    paletteQuery,
    setPaletteQuery,
    cheatsheetOpen,
    setCheatsheetOpen,
    catalogOpen,
    setCatalogOpen,
    composeOpen,
    setComposeOpen,
    sharedSessionOpen,
    setSharedSessionOpen,
    sessionSemanticsOpen,
    setSessionSemanticsOpen,
    draftReloadTick,
    setDraftReloadTick,
    serverSearchOpen,
    setServerSearchOpen,
    tourOpen,
    finishTour,
    inspectorOpen,
    setInspectorOpen,
    previewOpen,
    setPreviewOpen,
    previewPath,
    setPreviewPath,
    sessionsOpen,
    setSessionsOpen,
    railRoute,
    setRailRoute,
    selectedMessageId,
    setSelectedMessageId,
  } = createChatLayoutUiState(props);

  const { topbarOverflow, transcriptSearch, transcriptScroll, discoveryClient, paletteItems } =
    createChatLayoutServices(props);

  const {
    activeRow,
    inspectorTarget,
    toolCallsForInspector,
    connectionTone,
    onChat,
    showSessionsColumn,
    previewWorkspaceId,
    emptyTranscript,
    isNarrowViewport,
    selectFromSessionsColumn,
    secondaryChips,
  } = createChatLayoutDerivedState({
    props,
    railRoute,
    sessionsOpen,
    selectedMessageId,
    setSessionsOpen,
  });
  const { openSessionSemanticsPicker, handlePick } = createChatLayoutCommandWiring({
    props,
    onChat,
    paletteOpen,
    setPaletteOpen,
    cheatsheetOpen,
    setCheatsheetOpen,
    setCatalogOpen,
    setComposeOpen,
    setSharedSessionOpen,
    setSessionSemanticsOpen,
    setServerSearchOpen,
    setInspectorOpen,
    setSessionsOpen,
    setRailRoute,
    transcriptSearch,
  });

  return {
    activeDiff,
    setActiveDiff,
    paletteOpen,
    setPaletteOpen,
    paletteQuery,
    setPaletteQuery,
    cheatsheetOpen,
    setCheatsheetOpen,
    catalogOpen,
    composeOpen,
    sharedSessionOpen,
    sessionSemanticsOpen,
    draftReloadTick,
    setDraftReloadTick,
    serverSearchOpen,
    setServerSearchOpen,
    tourOpen,
    finishTour,
    topbarOverflow,
    transcriptSearch,
    inspectorOpen,
    setInspectorOpen,
    previewOpen,
    setPreviewOpen,
    previewPath,
    setPreviewPath,
    setSessionsOpen,
    railRoute,
    setRailRoute,
    selectedMessageId,
    setSelectedMessageId,
    transcriptScroll,
    discoveryClient,
    paletteItems,
    activeRow,
    inspectorTarget,
    toolCallsForInspector,
    connectionTone,
    onChat,
    showSessionsColumn,
    previewWorkspaceId,
    openSessionSemanticsPicker,
    handlePick,
    emptyTranscript,
    isNarrowViewport,
    selectFromSessionsColumn,
    secondaryChips,
    setSessionSemanticsOpen,
    setComposeOpen,
    setCatalogOpen,
    setSharedSessionOpen,
  };
}
